FROM python:3.11-slim

WORKDIR /app

# Erst requirements kopieren (für caching)
COPY meteor_webserver/requirements-docker.txt /app/

RUN pip install --no-cache-dir -r requirements-docker.txt

# Dann den restlichen Code
COPY meteor_webserver /app

CMD python app.py --docker >> /home/meteor/Documents/meteor-webserver/log-out/log.txt 2>&1
